### ISSUE TITLE
Help a noob get started

### ISSUE THREAD

**Issue by 68267a** [actualbudget/import-ynab5#1]
Hey, this looks like fun. I'm not a "developer" but I think I could handle this. The problem I have is that my experience is mostly in scripting (bash/powershell/etc). How do I get started in testing what I've written?

``Have Actual running locally and run `node index.js /path/to/data.json`.``

I'm on Windows. Do I need to install node.js or is it included in the Actual files?
I could use a 'prerequisites' section here: https://actualbudget.com/docs/developers/using-the-API/

**Comment by jlongster** [comment]
@accountnumber3 so sorry I missed this! I would love to help if you are still interested. Yeah, the docs could be improved.

Actual does not provide node. Running the app locally will run the server, and the client is completely separate. You will need to install node to run the code: https://nodejs.org/en/

You should get a `node` binary, and then you can run `node index.js <path-to-file>` after checking out this repo.

Is there anything else you want me to explain?

**Comment by jlongster** [comment]
@accountnumber3 still interested in this?

**Comment by cristianbostan** [comment]
Yes please

**Comment by amnuts** [comment]
Just submitted PR #13 which hopefully gives some helpful information in getting the importer up and running.
