### ISSUE TITLE
Cant download my budget file

### ISSUE THREAD

**Issue by Kinc4id** [actualbudget/import-ynab5#20]
Trying to get the ID of my budget from the nynab api results in

{"error":{"id":"404.1","name":"not_found","detail":"Invalid URI"}}

**Comment by Kinc4id** [comment]
For anyone else running into this problem I found a website that downloads the json from ynab for you.

https://ynab-json-exporter.netlify.app/#

With this I downloaded my budget from ynab and importet it in actual without any problems.

**Comment by SgtBatten** [comment]
@Kinc4id unfortunately it is now a restricted app. YNAB has blocked it from being authorised. :(

**Comment by trevdor** [comment]
@SgtBatten Were you ever able to get your budget file? If not, I'm curious if there's a step in [this repo's README](https://github.com/actualbudget/import-ynab5#exporting-from-ynab) that's stopping you.

@Kinc4id Is it fair to say your issue is resolved?

**Comment by Kinc4id** [comment]
@trevdor Well, kinda. I close this issue.
